// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

//import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "lib/openzeppelin-contracts/contracts/token/ERC20/IERC20.sol";
import "lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol";
import "lib/openzeppelin-contracts/contracts/access/Ownable.sol";
import "lib/openzeppelin-contracts/contracts/security/ReentrancyGuard.sol";

/// @title A shop staking contract
/// @author crypt0grapher
/// @notice this contract stakes SHOP tokens and allows users to earn rewards from the fees generated by the platform

contract StakedShop is ERC20, Ownable, ReentrancyGuard {
    event Snapshot(address indexed from, uint256 rewards, uint256 shopPrice);
    event Deposited(address indexed user, uint256 amount);
    event Withdrawn(address indexed user, uint256 amount);
    event Claimed(address indexed user, uint256 reward);

    IERC20 public constant shopToken = 0x99e186E8671DB8B10d45B7A1C430952a9FBE0D40;

    uint256 public minimumStake = 20000 * 10e18;
    uint256 public timeLock = 5 days;

    uint256 public epochDuration = 1 days;
    uint256 public rewardPool;

    struct EpochInfo {
        uint256 timestamp;
        uint256 rewards;
        uint256 totalStaked;
        uint256 shopPrice;
    }

    uint256 public lastSnapshotTime;
    uint256 public currentEpoch;
    mapping(uint256 => EpochInfo) public epochInfo;

    // user => epoch => total amount deposited during the epoch
    mapping(address => mapping(uint256 => uint256)) public deposits;

    mapping(address => bool) public isAutoCompounding;
    // a starting epoch for reward calculation for user - either last claimed or first deposit
    mapping(address => uint256) public lastClaimedEpoch;


    constructor() ReentrancyGuard() Ownable() ERC20("Staked SHOP", "xSHOP") {
        lastSnapshotTime = block.timestamp;
    }

    function setMinimumStake(uint256 _minimumStake) public onlyOwner {
        minimumStake = _minimumStake;
    }

    function setTimeLock(uint256 _timeLock) public onlyOwner {
        timeLock = _timeLock;
        lastAutoCompoundTime = block.timestamp;
    }

    function setAutoCompounding(bool _status) public {
        isAutoCompounding[msg.sender] = _status;
    }

    function deposit(uint256 amount) public {
        require(amount + balanceOf(msg.sender) > minimumStake, "Amount must be greater than 20K $SHOP");
        require(shopToken.transferFrom(msg.sender, address(this), amount), "Transfer failed");

        _updateStake(msg.sender, amount, true);

        emit Deposited(msg.sender, amount);
    }

    function withdraw(uint256 amount) public {
        require(balanceOf(msg.sender) >= amount, "Insufficient balance");

        updateStake(msg.sender, amount, false);

        require(shopToken.transfer(msg.sender, amount), "Transfer failed");

        emit Withdrawn(msg.sender, amount);
    }

    function claimReward() public {
        uint256 reward = calculateReward(msg.sender);
        require(!isAutoCompounding[msg.sender], "Auto-compounding is enabled");
        require(reward > 0, "No reward available");
        deposits[msg.sender].lastClaimedEpoch = currentEpoch;
        payable(msg.sender).transfer(reward);

        emit Claimed(msg.sender, reward);
    }

    function snapshot(uint256 _shopPrice) public payable nonReentrant {
        require(block.timestamp >= lastSnapshotTime + epochDuration - 5 minutes, "Too early for a new snapshot");
        require(msg.value > 0, "ETH amount must be greater than 0");
        currentEpoch[currentEpoch].rewards = msg.value;
        currentEpoch[currentEpoch].timestamp = block.timestamp;
        currentEpoch[currentEpoch].totalStaked = totalSupply();
        currentEpoch[currentEpoch].shopPrice = _shopPrice;
        currentEpoch++;
        emit Snapshot(msg.value, msg.sender, shopPrice);
    }

    function _updateStake(address user, uint256 amount, bool isDeposit) internal {
        uint256 currentEpoch = currentEpoch();
        if (isDeposit) {
            deposits[user][currentEpoch].amount += amount;
            _mint(user, amount);
        } else {
            remainingAmountToWithdraw = amount;
            for (uint256 i = 0; i <= currentEpoch; i++) {
                if (remainingAmountToWithdraw == 0) {
                    break;
                }
                uint256 amountToWithdraw = deposits[user][i].amount;
                if (amountToWithdraw > remainingAmountToWithdraw) {
                    amountToWithdraw = remainingAmountToWithdraw;
                }
                deposits[user][i].amount -= amountToWithdraw;
                remainingAmountToWithdraw -= amountToWithdraw;
            }
            deposits[user].amount = deposits[user].amount.sub(amount);
            _burn(user, amount);
        }
    }


    function calculateReward(address user) public view returns (uint256) {
        require(lastSnapshotTime + epochDuration < block.timestamp, "Too early to calculate rewards");
        uint256 reward = 0;
        uint256 userBalanceInEpoch = 0;
        for (uint256 i = deposits[msg.sender].lastClaimedEpoch; i < currentEpoch; i++) {
            userBalanceInEpoch += deposits[user][i].amount;
            uint256 epochReward = userBalanceInEpoch * epochInfo[i].rewards / epochInfo[i].totalStaked;
            reward += epochReward;
        }
        return reward;
    }

    // Mock function for demonstration purposes. In reality, you'd interact with a decentralized exchange contract here.
    function swapEthForShop(uint256 ethAmount) internal returns (uint256) {
        uint256 shopPrice = 0.000005 ether;  // Replace with actual price from an oracle
        uint256 shopAmount = ethAmount / shopPrice;
        return shopAmount;
    }

    function _beforeTokenTransfer(address from, address to, uint256 amount) internal override {
        require(from == address(0) || to == address(0), "Only stake or unstake");
    }


    function rescueETH(uint256 weiAmount) external {
        payable(_owner).transfer(weiAmount);
    }

    function rescueERC20(address tokenAdd, uint256 amount) external {
        IERC20(tokenAdd).transfer(_owner, amount);
    }


}
